spring.application.name=${APP_NAME}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.default_schema=${DB_NAME}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.defer-datasource-initialization=true
# Security
# NEVER
server.error.include-stacktrace=${INCLUDE_STACKTRACE}
server.error.include-message=${INCLUDE_MESSAGE}
logging.level.org.springframework.security=${LOGGING_SECURITY}
# log sql queries with params
logging.level.org.hibernate.SQL=${LOGGING_SQL_LEVEL}
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=${LOGGING_BINDER_LEVEL}
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL}
#spring.devtools.livereload.enabled=true
#spring.devtools.restart.enabled=true
#spring.devtools.restart.poll-interval=2s
#spring.devtools.restart.quiet-period=1s

jwt.secret=Zo04qlHoqhCF6tz1bBrXavqnHrTGkWI5pHxnXYTo1OHmEP1ViTk6savmM6IEmPNECDCDe85Cv45ik4rpa0fql3E2QHZ1HUXHFlkBPlC8f8B9uoyrmq25zn5fdjI09M5A2d1Juzw7Ja5T3EslulIS1ZA4b5hS7LxQ4DPt4aUt60ghONOfKbRUH06yUGc7BQK3MvpxWfuMS834NlhclVMS60ckJHzIlAUQY5bwdjnjMdG0QYFyz0MMbhjN4dLzyxdh
jwt.algorithm=HS256
jwt.expiration=864000000
app.allowed-urls=/v3/api-docs/**, /swagger-ui/**, /swagger-ui.html
app.auth-urls=/auth/**
app.allowed-origins=*

authentication.enabled=${AUTHENTICATION_ENABLED:true}
